image:
  file: ./Dockerfile
vscode:
  extensions:
  - golang.go
  - timonwong.shellcheck
ports:
  - port: 6080
    visibility: private
    onOpen: open-preview
additionalRepositories:
  - url: https://github.com/pop-os/launcher

tasks:
  - init: |
      go mod download
      cd frontend && npm install
